services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ${DOCKER_USERNAME}/docker-project-backend:latest
    container_name: momo-store-backend
    restart: unless-stopped
    environment:
      - LOG_LEVEL=info
      - NODE_ENV=production
    ports:
      - "8081:8081"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8081/health || exit 0"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 10s
    networks:
      - momo-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    read_only: true

    tmpfs:
      - /tmp

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ${DOCKER_USERNAME}/docker-project-frontend:latest
    container_name: momo-store-frontend
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/ || exit 0"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 40s
    networks:
      - momo-network
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 128M
    read_only: true
    volumes:
      - nginx-cache:/var/cache/nginx:rw
      - nginx-pid:/var/run:rw

    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx

networks:
  momo-network:
    driver: bridge

volumes:
  nginx-cache:
  nginx-pid:
