networks:
  momo-store-swarm:
    driver: overlay
    attachable: true

services:
  backend:
    image: lyandrei/docker-project-backend:latest
    cap_drop:
      - ALL
    expose:
      - "8081"
    networks:
      - momo-store-swarm
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8081/health"]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3
    deploy:
      replicas: 3
      resources:
        reservations:
          memory: 256M
        limits:
          memory: 512M
          cpus: '0.5'
    user: "1001:1001"

  frontend:
    image: lyandrei/docker-project-frontend:latest
    cap_add:
      - NET_BIND_SERVICE
    cap_drop:
      - ALL
    ports:
      - "80:80"
    networks:
      - momo-store-swarm
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3
    deploy:
      resources:
        reservations:
          memory: 128M
        limits:
          memory: 256M
          cpus: '0.25'
    user: "1001:1001"
    depends_on:
      backend:
        condition: service_healthy
