name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_scan_backend:
    name: back
    runs-on: ubuntu-latest
    steps:
      - name: clone
        uses: actions/checkout@v3

      - name: Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: int
        uses: docker/build-push-action@v4
        with:
          context: ./backend/
          push: false
          load: true
          tags: docker-project-backend:latest

      - name: Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker-project-backend:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL'

  build_and_scan_frontend:
    name: front
    runs-on: ubuntu-latest
    steps:
      - name: clonefront
        uses: actions/checkout@v3

      - name: Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: intfront
        uses: docker/build-push-action@v4
        with:
          context: ./frontend/
          push: false
          load: true
          tags: docker-project-frontend:latest

      - name: Trivyfront
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker-project-frontend:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL'

  push_to_docker_hub:
    name: Push Docker Hub
    runs-on: ubuntu-latest
    needs: [build_and_scan_backend, build_and_scan_frontend]
    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Back Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: ./backend/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/docker-project-backend:latest

      - name: Front Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: ./frontend/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/docker-project-frontend:latest

  run_with_docker_compose:
    name: Docker Compose
    runs-on: ubuntu-latest
    needs: push_to_docker_hub
    steps:
      - name: CloneCompose
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Auth Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Start Docker Compose
        uses: hoverkraft-tech/compose-action@v2.2.0
        with:
          compose-file: "./docker-compose.yml"
          down-flags: "--volumes"
          up-flags: "--build"
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
